# Required
version: 2

# Image to use
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Install requirements
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
